name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch for destroy'
        required: true
        default: 'main'
        type: string
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  AWS_REGION: ap-south-1
  TERRAFORM_VERSION: 1.6.0
  PYTHON_VERSION: 3.11

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch || github.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -input=false

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve -var="environment=${{ github.event.inputs.environment }}" \
            -var="project_name=myproject" \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}"
